language: node_js
node_js:
  - 5.6.x # Start at 5.6 to match package.json engines.
  - 5.7.x
  - 5.8.x
  - 5.9.x
  - 5.10.x
  - 5.11.x
  - 6.0.x
  - 6.1.x
  - node # The latest stable Node.js release.